import test from 'node:test';
import assert from 'node:assert/strict';
import sharp from 'sharp';
import {validImageUrl,imageName,storeImage,MAX_IMAGE_BYTES} from './media.js';
test('Media URLs accept only local assets and the trusted HTTPS ImgBB image host',()=>{for(const s of ['/images/hero.webp','https://i.ibb.co/abc/comfort.webp'])assert.ok(validImageUrl(s));for(const s of ['https://evil.test/a.png','http://i.ibb.co/a.png','https://i.ibb.co.evil.test/a.png','https://evil@i.ibb.co/a.png','/images/../data/nocte.sqlite','javascript:alert(1)'])assert.equal(validImageUrl(s),false)});
test('Image naming includes product or banner identity, not the original filename',()=>{assert.match(imageName('product','The Hybrid Mattress','product-123'),/^product-the-hybrid-mattress-product-123-[a-f0-9]+$/);assert.match(imageName('banner','Summer comfort','heroImage'),/^banner-summer-comfort-heroImage-/)});
test('ImgBB receives a server key, reencoded image and name; never an expiration',async()=>{const bytes=await sharp({create:{width:40,height:30,channels:3,background:'#123456'}}).png().toBuffer();let inspected=false;const result=await storeImage(bytes,'product-comfort-p123-abc',{key:'not-a-real-test-key',cloud:true,fetchImpl:async(url,options)=>{assert.equal(url,'https://api.imgbb.com/1/upload');assert.equal(options.body.get('key'),'not-a-real-test-key');assert.equal(options.body.get('name'),'product-comfort-p123-abc');assert.equal(options.body.has('expiration'),false);const image=options.body.get('image');assert.equal(image.type,'image/webp');assert.equal((await sharp(Buffer.from(await image.arrayBuffer())).metadata()).format,'webp');inspected=true;return {ok:true,json:async()=>({success:true,data:{id:'host-id',url:'https://i.ibb.co/host-id/photo.webp',delete_url:'https://ibb.co/host-id/private-delete-token'}})}}});assert.ok(inspected);assert.equal(result.provider,'imgbb');assert.equal(result.providerId,'host-id');assert.equal(result.width,40);assert.match(result.deleteUrl,/private-delete-token/)});
test('Vercel refuses disk fallback and invalid uploads before contacting ImgBB',async()=>{const good=await sharp({create:{width:2,height:2,channels:3,background:'#fff'}}).png().toBuffer();await assert.rejects(storeImage(good,'test',{key:'',cloud:true}),/not configured/);await assert.rejects(storeImage(Buffer.from('<svg/>'),'test',{key:'x',cloud:true}),/valid JPEG/);await assert.rejects(storeImage(Buffer.alloc(MAX_IMAGE_BYTES+1),'test',{key:'x',cloud:true}),/3 MB/)});
test('Untrusted ImgBB response URLs and provider errors do not become published images',async()=>{const bytes=await sharp({create:{width:2,height:2,channels:3,background:'#fff'}}).png().toBuffer();await assert.rejects(storeImage(bytes,'test',{key:'x',cloud:true,fetchImpl:async()=>({ok:true,json:async()=>({success:true,data:{id:'x',url:'https://attacker.test/image.webp'}})})}),/could not save/)});
