import {chromium,expect} from '@playwright/test';
const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1440,height:1000}});let errors=[];page.on('pageerror',e=>errors.push(e.message));
const root=process.env.TEST_ROOT||'http://127.0.0.1:3000';
try{
await page.goto(root);await page.getByRole('button',{name:'Search products',exact:true}).click();await page.getByRole('dialog').getByRole('combobox',{name:'Search products'}).fill('hybrid');await expect(page.getByRole('dialog').getByRole('heading',{name:'The Hybrid'})).toBeVisible();await page.keyboard.press('Escape');console.log('PASS search and accessible modal Escape');
await page.goto(root+'/account');await page.getByRole('button',{name:'Create an account',exact:true}).click();await page.getByLabel('Your name').fill('Demo Tester');const email='tester'+Date.now()+'@example.com';await page.getByLabel('Email address',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill('DemoTester!2026');await page.getByRole('button',{name:'Create your account'}).click();await expect(page.getByRole('heading',{name:'Hello, Demo.'})).toBeVisible();console.log('PASS registration and account');
await page.goto(root+'/product/hybrid-mattress');await expect(page.getByRole('heading',{name:'The Hybrid',exact:true})).toBeVisible();await page.getByRole('button',{name:'King 72 × 78 in'}).click();await page.getByRole('button',{name:'Firm',exact:true}).click();await page.getByRole('button',{name:'10 inches',exact:true}).click();await expect(page.locator('.pdp-price')).toContainText('₹31,799');await page.getByRole('button',{name:'Save product',exact:true}).click();await page.getByRole('button',{name:'Compare',exact:true}).click();await page.getByRole('button',{name:'Add to bag',exact:true}).first().click();await expect(page.getByRole('dialog')).toBeVisible();await expect(page.getByRole('dialog')).toContainText('King · 10″ · Firm');await page.getByRole('button',{name:'View your bag',exact:true}).click();await expect(page).toHaveURL(root+'/cart');await page.getByRole('textbox',{name:'Coupon code'}).fill('INVALID');await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.locator('.form-error')).toContainText('invalid');await page.getByRole('textbox',{name:'Coupon code'}).fill('REST10');await page.getByRole('button',{name:'Apply',exact:true}).click();await expect(page.locator('.discount-line')).toContainText('REST10');await page.getByRole('button',{name:'Continue to checkout'}).click();console.log('PASS variants, wishlist, compare, cart and coupon');
await page.getByLabel('Full name',{exact:true}).fill('Demo Tester');await page.getByLabel('Email address',{exact:true}).fill(email);await page.getByLabel('Mobile number').fill('9876543210');await page.getByRole('button',{name:'Continue to shipping'}).click();await page.getByLabel('Street address, building & apartment').fill('24 Demo Garden Road');await page.getByLabel('City',{exact:true}).fill('Patna');await page.getByLabel('State',{exact:true}).fill('Bihar');await page.getByLabel('PIN code',{exact:true}).fill('800001');await page.getByRole('button',{name:'Review order',exact:true}).click();await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Submit order',exact:true}).click();await expect(page.getByRole('heading',{name:'Your order is received.'})).toBeVisible();const orderId=await page.locator('.receipt-heading h2').innerText();await page.goto(root+'/tracking?id='+orderId+'&email='+encodeURIComponent(email));await expect(page.locator('.tracking-result')).toContainText('Preview — unpaid');await expect(page.locator('.tracking-result')).toContainText('The Hybrid');console.log('PASS three-step checkout, confirmation and authenticated tracking');
await page.goto(root+'/wishlist');await expect(page.locator('.product-card')).toHaveCount(1);await page.goto(root+'/compare');await expect(page.locator('.comparison-table')).toContainText('The Hybrid');console.log('PASS persisted wishlist and comparison');
await page.goto(root+'/quiz');for(let i=0;i<8;i++){await page.locator('.quiz-options>button').nth(i===6?2:0).click();await page.getByRole('button',{name:i===7?'Find my match':'Continue',exact:true}).click()}await expect(page.getByRole('heading',{name:'Hello, better nights.'})).toBeVisible();await expect(page.locator('.match-score')).toContainText('% preference match');console.log('PASS eight-step recommendation wizard');
await page.goto(root+'/support');await page.getByLabel('Subject',{exact:true}).fill('Test delivery request');await page.getByLabel('Tell us a little more').fill('Please tell me more about the delivery process for my demo order.');await page.getByRole('button',{name:'Send your message'}).click();await expect(page.getByRole('heading',{name:'A little help is on its way.'})).toBeVisible();console.log('PASS customer support');
await page.goto(root+'/account');await page.getByRole('button',{name:'Sign out',exact:true}).click();await page.goto(root+'/owner');await page.getByRole('button',{name:'Use demo owner credentials'}).click();await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL('**/owner/dashboard');await expect(page.locator('.kpi-card')).toHaveCount(4);console.log('PASS owner login and dashboard');
await page.goto(root+'/owner/products');await page.locator('.admin-table tbody tr').filter({hasText:'The Essential'}).getByRole('button',{name:'Edit',exact:true}).click();await page.getByRole('dialog').getByLabel('Product badge').fill('Bestseller');await page.getByRole('button',{name:'Save changes',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);console.log('PASS product editor save');
await page.goto(root+'/owner/inventory');await page.locator('.admin-table tbody tr').filter({hasText:'The Essential'}).getByRole('button',{name:'Adjust',exact:true}).click();await page.getByLabel('Stock adjustment (+ to add, − to remove)').fill('0');await page.getByLabel('Reason / supplier reference').fill('QA stock verification — no quantity change');await page.getByRole('button',{name:'Save changes',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);console.log('PASS audited inventory adjustment');
await page.goto(root+'/owner/settings');await page.getByRole('button',{name:'Homepage',exact:true}).click();await expect(page.getByLabel('Hero headline')).toHaveValue('A better night.\nA brighter you.');await page.getByRole('button',{name:'Save changes',exact:true}).click();await expect(page.getByRole('status')).toContainText('saved');console.log('PASS owner settings saved');
await page.setViewportSize({width:390,height:844});await page.goto(root+'/owner/products');await page.getByRole('button',{name:'Open owner navigation'}).click();await expect(page.locator('.admin-sidebar.open')).toBeVisible();await page.getByRole('button',{name:'Close admin navigation'}).click();await page.getByRole('button',{name:'dark theme',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await page.screenshot({path:'qa/owner-mobile-dark.png',fullPage:true});console.log('PASS mobile owner navigation and dark mode');
await page.goto(root+'/account');await page.getByLabel('Email address',{exact:true}).fill(email);await page.getByLabel('Password',{exact:true}).fill('DemoTester!2026');await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('heading',{name:'Hello, Demo.'})).toBeVisible();
await page.goto(root+'/product/pillow-mattress');await expect(page.locator('.accessory-info')).toBeVisible();await page.locator('.pdp-purchase').getByRole('button',{name:'Add to bag'}).click();await page.getByRole('button',{name:'Continue to checkout',exact:true}).click();await expect(page.locator('.order-summary')).toContainText('₹1,999');await expect(page.locator('.form-error')).toHaveCount(0);console.log('PASS mobile accessory checkout');
await page.goto(root);await page.getByRole('button',{name:'light theme',exact:true}).click();await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'qa/mobile-final.png',fullPage:true});
console.log('BROWSER ERRORS',errors);console.log('ALL FLOW CHECKS PASSED');
}catch(e){console.error('FLOW FAILED',e.message);console.error('PAGE ERRORS',errors);await page.screenshot({path:'qa/flow-failure.png',fullPage:true});process.exitCode=1}finally{await browser.close()}
